### ISSUE TITLE
`ModuleError: Failed to resolve dependencies` (`npm`, `zod`)

### ISSUE THREAD

**Issue by sz3lbi** [SAP-samples/ui5-typescript-tutorial#16]
Hi,
I want to use `zod` along with the UI5. Therefore, I tried to go with the exercise 4.  
What steps have I done?  
1. Installed `zod`: `npm install zod --save-dev` (also tried as a normal dependency, not a dev one, but no difference).
2. Installed `ui5-tooling-modules`: `npm install ui5-tooling-modules --save-dev`
3. Edited the `ui5.yaml` as described in the exercise (full contents of the file below).
4. Imported `zod` into a TypeScript file.
5. Started the project with `npm run start`.

`devDependencies` in `package.json`:
```json
"devDependencies": {
  "@babel/eslint-parser": "7.14.7",
  "@sap-ux/eslint-plugin-fiori-tools": "^0.2.0",
  "@sap-ux/ui5-middleware-fe-mockserver": "2",
  "@sap/ux-ui5-tooling": "1",
  "@sapui5/ts-types-esm": "~1.108.22",
  "@typescript-eslint/eslint-plugin": "^5.59.0",
  "@typescript-eslint/parser": "^5.59.0",
  "@ui5/cli": "^3.0.0",
  "eslint": "7.32.0",
  "eslint-plugin-fiori-custom": "2.6.7",
  "typescript": "^5.1.6",
  "ui5-tooling-modules": "^3.0.7",
  "ui5-tooling-transpile": "^3.2.0",
  "zod": "^3.22.2"
},
```

`ui5.yaml`:
```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.1"
metadata:
  name: XXX
type: application
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: true # If set to true, certificate errors will be ignored. E.g. self-signed certificates will be accepted
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
        backend:
          - path: /sap
            url: XXX
            client: "XXX"
            destination: XXX
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: webapp
        delay: 300
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
      configuration:
        debug: true
        excludePatterns:
          - /Component-preload.js
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        component: XXX
        ui5Theme: sap_horizon
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        addToNamespace: true
    - name: ui5-tooling-transpile-task
      afterTask: replaceVersion
      configuration:
        debug: true
```

`zod` usage:
```ts
import { z } from "zod";

export const oCommiAreas = z.object({
  Area: z.string().max(30),
  Arbpl: z.string().max(8),
  AreaDescr: z.string().max(40),
  Target: z.number().int(),
});

export type CommiAreas = z.infer<typeof oCommiAreas>;
```

I get the following error in the browser's Dev Tools:
`Uncaught (in promise) ModuleError: Failed to resolve dependencies of '.../controller/MainView.controller.js'`
![ModuleError](https://github.com/SAP-samples/ui5-typescript-tutorial/assets/8168846/da66d252-77ad-4483-aa19-92f40e3d761b)

The sources of the page in the Dev Tools look like this. There is no `zod.js` file anywhere.
![image](https://github.com/SAP-samples/ui5-typescript-tutorial/assets/8168846/67dd6f13-5f6a-4670-967a-a01d8e446a80)

According to [zod.dev](https://zod.dev/), zod has "zero dependencies" and "works in Node.js and all modern browsers".  
Could you please help me with this issue?

**Comment by akudev** [comment]
@petermuessig is the creator of ui5-tooling-modules, but as a first check: when you do `npm run build`, does zod then show up in the dist folder below "thirdparty"?

What I did (with some success):
- cloned this repo
- went into this directory: https://github.com/SAP-samples/ui5-typescript-tutorial/tree/main/exercises/ex4/com.myorg.myapp
- `npm i`
- `npm install zod --save-dev`
- In App.controller.ts added:
  - `import * as zod from "zod";`
  - `var x = zod.ZodAny.name` (well, just make sure to have any code added that actually uses zod to prevent it from being optimized away)
- `npm run build`

Result 1: zod is present in the build results (and should also be available at runtime in the dev server, albeit not visible in the dev tools when not loaded)

Result 2: there is still an error in the console, but it looks slightly different: zod.js is loaded and executed but fails:
![image](https://github.com/SAP-samples/ui5-typescript-tutorial/assets/4866568/1d788876-e7f4-4d05-81ff-f65af2c630d3)

Result 3: in the build log there is an error, but not sure from where and how relevant it is, as zod IS present:
```
info com.myorg.myapp › Running task generateComponentPreload...
error lbt:analyzer:JSModuleAnalyzer Unhandled AST node type MetaProperty Node {
  type: 'MetaProperty',
  start: 2555,
  end: 2565,
  meta: Node { type: 'Identifier', start: 2555, end: 2558, name: 'new' },
  property: Node { type: 'Identifier', start: 2559, end: 2565, name: 'target' }
}
error lbt:resources:ResourcePool Failed to analyze com/myorg/myapp/thirdparty/zod.js: Unhandled AST node type MetaProperty
info ProjectBuilder Build succeeded in 1.05 s
info ProjectBuilder Executing cleanup tasks..
```

Not sure whether error 2 results from error 3. @petermuessig : any idea?

**Comment by petermuessig** [comment]
I'll prepare a solution, the problem is that the `zod` already exposes the `__esModule` property to its exports and we try to redefine it to mark the module as former esModule and this leads to an error... We need to try..catch the redefine of the marker...

**Comment by petermuessig** [comment]
Please try with `ui5-tooling-modules` version `3.0.8`

**Comment by akudev** [comment]
In other words: your yaml contains this section
```
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
```
which causes the UI5 tooling to load everything below the path `/resources` from ui5.sap.com. But of course zod does not exist there. Hence the suggestion from @petermuessig to set the `data-sap-ui-resourceroots` to load zod from somewhere else.

BUT: this is a client-side setting and simply setting something like
```
data-sap-ui-resourceroots='{
		"com.myorg.myapp": "./",
		"zod": "./resources/zod"
	}'
```
or so will probably not work, because the path requested from the (UI5) server is still `/resources/...`. Or am I wrong? Hence one would have to choose a different beginning of the path and also configure something in the yaml for this prefix.

Or simply get rid of the setting with the UI5 URL in the yaml.
